- name: Just a workaround
  hosts: all
  tasks:
  - name: Prepare System(s)
    ansible.builtin.import_playbook: 01_config_system.yml

  - name: Configure Application
    ansible.builtin.import_playbook: 02_config_application.yml
